### PR TITLE
Initial cm-12 bringup

### PR DESCRIPTION
**Pull request by HardLight**
Cm12 changes for lotus

Change-Id: Ic5152cc9572b5f4416279b3545de7a64a505868b

### CODE REVIEW

**Comment by HardLight** [comment]
For now rom boots until Android upgrading > Starting Apps and hangs.
Logcat shows:
Waiting for sevice media.audio_policy...
AudioPolicyService not published, waiting...

**Comment by GarciaLnk** [comment]
Thank you

**Comment by Nathanael-Mtd** [comment]
Thanks @HardLight !

**Comment by alwaysadeel** [comment]
@HardLight see this https://github.com/XperiaSTE/android_vendor_sony/commit/cfc2d5dbc8c2f0cbfedf23345423a275e9825769

**Comment by HardLight** [comment]
Thanks @alwaysadeel it worked! I've made pull request for lotus https://github.com/XperiaSTE/android_vendor_sony/pull/4

**Pull request merged**
